import type { Metadata } from "next";
import { PageHero } from "@/components/site/page-hero";
import { Reveal } from "@/components/motion/reveal";
import { siteConfig } from "@/lib/data";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and Conditions for using the Sai Baba Transport website.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using this website, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use this website.",
  },
  {
    title: "2. Website Purpose",
    body: "This website provides general information about Sai Baba Transport's services, branch network, and enables enquiries, quote requests and partnership registrations. It does not constitute a binding offer of transportation services.",
  },
  {
    title: "3. Transport Estimation Calculator",
    body: "Estimates generated by the online transport calculator are indicative only and provided for lead-generation purposes. They do not constitute a final quotation. Final freight charges depend on actual route, vehicle availability, fuel and toll charges, loading/unloading, material type, market conditions and our commercial terms, and will be confirmed separately by our team.",
  },
  {
    title: "4. Accuracy of Information",
    body: "We aim to keep website content accurate and up to date, including branch details, services and fleet information, but we do not guarantee that all information is free of errors or omissions at all times.",
  },
  {
    title: "5. Third-Party Links",
    body: "This website may link to third-party systems, including our existing CRM and ERP platforms. We are not responsible for the content, availability or practices of third-party websites or systems.",
  },
  {
    title: "6. Intellectual Property",
    body: "The Sai Baba Transport name, logo and website content are the property of Sai Baba Transport and may not be used without prior written permission, except as necessary to use this website for its intended purpose.",
  },
  {
    title: "7. Limitation of Liability",
    body: "Sai Baba Transport shall not be liable for any indirect, incidental or consequential damages arising from the use of this website, including reliance on indicative estimates provided by the transport calculator.",
  },
  {
    title: "8. Governing Law",
    body: "These Terms & Conditions are governed by the laws of India, and any disputes shall be subject to the jurisdiction of the courts where our head office is located.",
  },
  {
    title: "9. Contact Us",
    body: `For questions about these Terms & Conditions, contact us at ${siteConfig.email} or ${siteConfig.phone}.`,
  },
];

export default function TermsPage() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        title="Terms & Conditions"
        description="Please read these terms carefully before using the Sai Baba Transport website."
        breadcrumbs={[{ label: "Home", href: "/" }, { label: "Terms & Conditions" }]}
      />
      <section className="py-20 sm:py-28">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <Reveal className="rounded-xl border border-dashed border-primary/30 bg-accent/50 p-4 text-sm text-foreground/70">
            This is placeholder terms content for a website template and has
            not been reviewed by legal counsel. Please have this page
            reviewed and finalized by a qualified professional before
            publishing the live site.
          </Reveal>
          <p className="mt-6 text-sm text-muted-foreground">Last updated: August 2026</p>
          <div className="mt-8 space-y-8">
            {sections.map((s) => (
              <Reveal key={s.title}>
                <h2 className="text-lg font-semibold text-brand-charcoal">{s.title}</h2>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.body}</p>
              </Reveal>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
